/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/mman.h>
#include <termios.h>
#include <string.h>
#include <unistd.h>
/* Header for class com_example_gimgiyun_speedgame2_TextLcd */

#ifndef _Included_com_example_gimgiyun_speedgame2_TextLcd
#define _Included_com_example_gimgiyun_speedgame2_TextLcd

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gimgiyun_speedgame2_TextLcd
 * Method:    control
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_gimgiyun_speedgame2_TextLcd_control
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_gimgiyun_speedgame2_TextLcd
 * Method:    clear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_gimgiyun_speedgame2_TextLcd_clear
  (JNIEnv *, jobject);

/*
 * Class:     com_example_gimgiyun_speedgame2_TextLcd
 * Method:    IOCtlDisplay
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_gimgiyun_speedgame2_TextLcd_IOCtlDisplay
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_gimgiyun_speedgame2_TextLcd
 * Method:    IOCtlReturnHome
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_gimgiyun_speedgame2_TextLcd_IOCtlReturnHome
  (JNIEnv *, jobject);

/*
 * Class:     com_example_gimgiyun_speedgame2_TextLcd
 * Method:    IOCtlCursor
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_gimgiyun_speedgame2_TextLcd_IOCtlCursor
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_gimgiyun_speedgame2_TextLcd
 * Method:    IOCtlBlink
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_example_gimgiyun_speedgame2_TextLcd_IOCtlBlink
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
