/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
/* Header for class com_example_gimgiyun_speedgame2_DotMatrix */

#ifndef _Included_com_example_gimgiyun_speedgame2_DotMatrix
#define _Included_com_example_gimgiyun_speedgame2_DotMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gimgiyun_speedgame2_DotMatrix
 * Method:    openDotMatrix
 * Signature: ()Z
 */

JNIEXPORT jboolean JNICALL Java_com_example_gimgiyun_speedgame2_DotMatrix_openDotMatrix
    (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_example_gimgiyun_speedgame2_DotMatrix_Control
  (JNIEnv *, jobject, jstring);

//JNIEXPORT jboolean JNICALL Java_com_example_gimgiyun_speedgame2_DotMatrix_Close
//  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
