/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_gimgiyun_speedgame2_LED */

#ifndef _Included_com_example_gimgiyun_speedgame2_LED
#define _Included_com_example_gimgiyun_speedgame2_LED
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gimgiyun_speedgame2_LED
 * Method:    Control
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_gimgiyun_speedgame2_LED_Control
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
